// AUTO-GENERATED by TestCodegen.cs from support_ticket_fsm.json
// DO NOT EDIT MANUALLY.

using System;
using System.Collections.Generic;

public static class GeneratedSupportTests
{
    static readonly Dictionary<(string, string), string> Transitions = new()
    {
        [("Open", "Assign")] = "Assigned",
        [("Assigned", "Start")] = "InProgress",
        [("InProgress", "Resolve")] = "Resolved",
        [("Resolved", "Close")] = "Closed",
        [("Resolved", "Reopen")] = "Assigned",
    };

    static string Next(string state, string evt)
    {
        if (Transitions.TryGetValue((state, evt), out var next)) return next;
        throw new InvalidOperationException($"Illegal transition: {state} + {evt}");
    }

    public static int Run()
    {
        int passed = 0, total = 0;

        void Assert(string name, Func<bool> check)
        {
            total++;
            bool ok;
            try { ok = check(); } catch { ok = false; }
            if (ok) passed++;
            Console.WriteLine($"  [{(ok ? "PASS" : "FAIL")}] {name}");
        }

        // === Valid transition tests ===
        Console.WriteLine("-- Valid transitions --");
        Assert("Open + Assign -> Assigned",
            () => Next("Open", "Assign") == "Assigned");
        Assert("Assigned + Start -> InProgress",
            () => Next("Assigned", "Start") == "InProgress");
        Assert("InProgress + Resolve -> Resolved",
            () => Next("InProgress", "Resolve") == "Resolved");
        Assert("Resolved + Close -> Closed",
            () => Next("Resolved", "Close") == "Closed");
        Assert("Resolved + Reopen -> Assigned",
            () => Next("Resolved", "Reopen") == "Assigned");

        // === Invalid transition tests ===
        Console.WriteLine("-- Invalid transitions --");
        Assert("Open + Start throws (invalid)",
            () => {
                try { Next("Open", "Start"); return false; }
                catch (InvalidOperationException) { return true; }
            });
        Assert("Open + Resolve throws (invalid)",
            () => {
                try { Next("Open", "Resolve"); return false; }
                catch (InvalidOperationException) { return true; }
            });
        Assert("Open + Close throws (invalid)",
            () => {
                try { Next("Open", "Close"); return false; }
                catch (InvalidOperationException) { return true; }
            });
        Assert("Open + Reopen throws (invalid)",
            () => {
                try { Next("Open", "Reopen"); return false; }
                catch (InvalidOperationException) { return true; }
            });
        Assert("Assigned + Assign throws (invalid)",
            () => {
                try { Next("Assigned", "Assign"); return false; }
                catch (InvalidOperationException) { return true; }
            });

        // === Policy tests ===
        Console.WriteLine("-- Policy behavior --");
        Assert("Unknown policy is 'throw' — throws on unknown",
            () => {
                try { Next("NonExistent", "WhoKnows"); return false; }
                catch (InvalidOperationException) { return true; }
            });

        Console.WriteLine($"\nPassed: {passed}/{total}");
        return passed == total ? 0 : 1;
    }
}
