// TestCodegen.cs — генератор тестового шару з FSM DSL.
// Читає support_ticket_fsm.json і пише GeneratedSupportTests.cs.
// Три категорії тестів:
//   1. Valid transitions   — кожен legal transition перевіряється
//   2. Invalid transitions — пара (state, event) поза таблицею → виняток
//   3. Policy tests        — перевірка unknownPolicy із моделі

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;

var modelPath  = "support_ticket_fsm.json";
var outputPath = "GeneratedSupportTests.cs";

var model = JsonSerializer.Deserialize<FsmModel>(File.ReadAllText(modelPath),
    new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
    ?? throw new InvalidOperationException("Failed to parse model");

var sb = new StringBuilder();

sb.AppendLine("// AUTO-GENERATED by TestCodegen.cs from support_ticket_fsm.json");
sb.AppendLine("// DO NOT EDIT MANUALLY.");
sb.AppendLine();
sb.AppendLine("using System;");
sb.AppendLine("using System.Collections.Generic;");
sb.AppendLine();
sb.AppendLine("public static class GeneratedSupportTests");
sb.AppendLine("{");

// Embedded runtime (inline для самодостатнього тестового файлу)
sb.AppendLine("    static readonly Dictionary<(string, string), string> Transitions = new()");
sb.AppendLine("    {");
foreach (var t in model.Transitions)
    sb.AppendLine($"        [(\"{t.From}\", \"{t.Event}\")] = \"{t.To}\",");
sb.AppendLine("    };");
sb.AppendLine();

sb.AppendLine("    static string Next(string state, string evt)");
sb.AppendLine("    {");
sb.AppendLine("        if (Transitions.TryGetValue((state, evt), out var next)) return next;");
sb.AppendLine($"        throw new InvalidOperationException($\"Illegal transition: {{state}} + {{evt}}\");");
sb.AppendLine("    }");
sb.AppendLine();

sb.AppendLine("    public static int Run()");
sb.AppendLine("    {");
sb.AppendLine("        int passed = 0, total = 0;");
sb.AppendLine();
sb.AppendLine("        void Assert(string name, Func<bool> check)");
sb.AppendLine("        {");
sb.AppendLine("            total++;");
sb.AppendLine("            bool ok;");
sb.AppendLine("            try { ok = check(); } catch { ok = false; }");
sb.AppendLine("            if (ok) passed++;");
sb.AppendLine("            Console.WriteLine($\"  [{(ok ? \\\"PASS\\\" : \\\"FAIL\\\")}] {name}\");");
sb.AppendLine("        }");
sb.AppendLine();

// === 1. Valid transition tests ===
sb.AppendLine("        // === Valid transition tests ===");
sb.AppendLine("        Console.WriteLine(\"-- Valid transitions --\");");
foreach (var t in model.Transitions)
{
    sb.AppendLine($"        Assert(\"{t.From} + {t.Event} -> {t.To}\",");
    sb.AppendLine($"            () => Next(\"{t.From}\", \"{t.Event}\") == \"{t.To}\");");
}
sb.AppendLine();

// === 2. Invalid transition tests ===
sb.AppendLine("        // === Invalid transition tests ===");
sb.AppendLine("        Console.WriteLine(\"-- Invalid transitions --\");");

// Знайдемо пари (state, event), для яких немає transition. Беремо до 3 прикладів.
var validPairs = new HashSet<(string, string)>(
    model.Transitions.Select(t => (t.From, t.Event)));
var invalidPairs = new List<(string, string)>();
foreach (var s in model.States)
    foreach (var e in model.Events)
        if (!validPairs.Contains((s, e)))
            invalidPairs.Add((s, e));

foreach (var (s, e) in invalidPairs.Take(5))
{
    sb.AppendLine($"        Assert(\"{s} + {e} throws (invalid)\",");
    sb.AppendLine($"            () => {{");
    sb.AppendLine($"                try {{ Next(\"{s}\", \"{e}\"); return false; }}");
    sb.AppendLine($"                catch (InvalidOperationException) {{ return true; }}");
    sb.AppendLine($"            }});");
}
sb.AppendLine();

// === 3. Policy tests ===
sb.AppendLine("        // === Policy tests ===");
sb.AppendLine("        Console.WriteLine(\"-- Policy behavior --\");");
sb.AppendLine($"        Assert(\"Unknown policy is '{model.UnknownPolicy}' — throws on unknown\",");
sb.AppendLine("            () => {");
sb.AppendLine("                try { Next(\"NonExistent\", \"WhoKnows\"); return false; }");
sb.AppendLine("                catch (InvalidOperationException) { return true; }");
sb.AppendLine("            });");
sb.AppendLine();

sb.AppendLine("        Console.WriteLine($\"\\nPassed: {passed}/{total}\");");
sb.AppendLine("        return passed == total ? 0 : 1;");
sb.AppendLine("    }");
sb.AppendLine("}");

File.WriteAllText(outputPath, sb.ToString());
Console.WriteLine($"Generated {outputPath} from {modelPath}");
Console.WriteLine($"  valid tests:   {model.Transitions.Count}");
Console.WriteLine($"  invalid tests: {Math.Min(5, invalidPairs.Count)} (of {invalidPairs.Count} possible)");
Console.WriteLine($"  policy tests:  1");

// ===== Типи =====

record FsmModel(
    string Name,
    string Initial,
    string UnknownPolicy,
    List<string> States,
    List<string> Events,
    List<Transition> Transitions);

record Transition(string From, string Event, string To);
