// Codegen.cs — генератор runtime з FSM DSL.
// Запуск: dotnet run
// Читає warehouse_flow_fsm.json і пише GeneratedWarehouseRuntime.cs.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.Json;

var modelPath  = "warehouse_flow_fsm.json";
var outputPath = "GeneratedWarehouseRuntime.cs";

var model = JsonSerializer.Deserialize<FsmModel>(File.ReadAllText(modelPath),
    new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
    ?? throw new InvalidOperationException("Failed to parse model");

var sb = new StringBuilder();

sb.AppendLine("// AUTO-GENERATED by Codegen.cs from warehouse_flow_fsm.json");
sb.AppendLine("// DO NOT EDIT MANUALLY — changes will be lost on regeneration.");
sb.AppendLine();
sb.AppendLine("using System;");
sb.AppendLine("using System.Collections.Generic;");
sb.AppendLine();
sb.AppendLine($"public static class GeneratedWarehouseRuntime");
sb.AppendLine("{");
sb.AppendLine($"    public const string InitialState = \"{model.Initial}\";");
sb.AppendLine();

// Transition map
sb.AppendLine("    // Transition map: (state, event) -> next state");
sb.AppendLine("    public static readonly Dictionary<(string, string), string> Transitions = new()");
sb.AppendLine("    {");
foreach (var t in model.Transitions)
    sb.AppendLine($"        [(\"{t.From}\", \"{t.Event}\")] = \"{t.To}\",");
sb.AppendLine("    };");
sb.AppendLine();

// Next() method
sb.AppendLine("    // Public API");
sb.AppendLine("    public static string Next(string state, string evt)");
sb.AppendLine("    {");
sb.AppendLine("        if (Transitions.TryGetValue((state, evt), out var next))");
sb.AppendLine("            return next;");
sb.AppendLine();

// Unknown policy handling
sb.AppendLine($"        // Unknown policy from DSL: {model.UnknownPolicy}");
if (model.UnknownPolicy == "throw")
{
    sb.AppendLine("        throw new InvalidOperationException(");
    sb.AppendLine("            $\"Illegal transition: {state} + {evt}\");");
}
else if (model.UnknownPolicy == "ignore")
{
    sb.AppendLine("        return state; // self-loop");
}
else
{
    sb.AppendLine($"        throw new InvalidOperationException(\"Unknown policy: {model.UnknownPolicy}\");");
}

sb.AppendLine("    }");
sb.AppendLine("}");

File.WriteAllText(outputPath, sb.ToString());
Console.WriteLine($"Generated {outputPath} from {modelPath}");
Console.WriteLine($"  states:      {model.States.Count}");
Console.WriteLine($"  events:      {model.Events.Count}");
Console.WriteLine($"  transitions: {model.Transitions.Count}");
Console.WriteLine($"  policy:      {model.UnknownPolicy}");

// ===== Типи =====

record FsmModel(
    string Name,
    string Initial,
    string UnknownPolicy,
    List<string> States,
    List<string> Events,
    List<Transition> Transitions);

record Transition(string From, string Event, string To);
