// AUTO-GENERATED by Codegen.cs from warehouse_flow_fsm.json
// DO NOT EDIT MANUALLY — changes will be lost on regeneration.

using System;
using System.Collections.Generic;

public static class GeneratedWarehouseRuntime
{
    public const string InitialState = "Idle";

    // Transition map: (state, event) -> next state
    public static readonly Dictionary<(string, string), string> Transitions = new()
    {
        [("Idle", "Receive")] = "Receiving",
        [("Receiving", "Store")] = "Storing",
        [("Storing", "Pick")] = "Picking",
        [("Picking", "Ship")] = "Shipping",
        [("Shipping", "Done")] = "Idle",
        [("Idle", "Fault")] = "Error",
        [("Storing", "Fault")] = "Error",
        [("Error", "Reset")] = "Idle",
    };

    // Public API
    public static string Next(string state, string evt)
    {
        if (Transitions.TryGetValue((state, evt), out var next))
            return next;

        // Unknown policy from DSL: throw
        throw new InvalidOperationException(
            $"Illegal transition: {state} + {evt}");
    }
}
