// AUTO-GENERATED by Codegen.cs from example_fsm.json
// DO NOT EDIT MANUALLY — changes will be lost on regeneration.
//
// Це приклад generated файлу. Маркери:
//   1. Префікс імені класу — Generated*
//   2. Коментар у першому рядку — AUTO-GENERATED
//   3. Структура містить лише машинно згенерований код (Dictionary, switch)

using System;
using System.Collections.Generic;

public static class GeneratedExampleRuntime
{
    public static readonly Dictionary<(string, string), string> Transitions = new()
    {
        [("Idle", "Start")] = "Running",
        [("Running", "Stop")] = "Idle",
    };

    public static string Next(string state, string evt)
    {
        if (Transitions.TryGetValue((state, evt), out var next))
            return next;
        throw new InvalidOperationException($"Illegal: {state} + {evt}");
    }
}
