// fsmgen — Universal FSM code generator CLI.
//
// Usage:
//   fsmgen generate-runtime <modelPath> <outDir>
//   fsmgen generate-tests   <modelPath> <outDir>
//   fsmgen all              <modelPath> <outDir>
//
// Один інструмент для будь-якої моделі. Перед генерацією — semantic check.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;

if (args.Length != 3)
{
    PrintUsage();
    return 1;
}

var command  = args[0];
var modelPath = args[1];
var outDir    = args[2];

if (!File.Exists(modelPath))
{
    Console.Error.WriteLine($"Model file not found: {modelPath}");
    return 2;
}

Directory.CreateDirectory(outDir);

var model = JsonSerializer.Deserialize<FsmModel>(File.ReadAllText(modelPath),
    new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
    ?? throw new InvalidOperationException("Failed to parse model");

// === Semantic check — обов'язково перед генерацією ===
var errors = SemanticCheck(model);
if (errors.Count > 0)
{
    Console.Error.WriteLine($"Semantic check failed for {modelPath}:");
    errors.ForEach(e => Console.Error.WriteLine($"  [ERROR] {e}"));
    return 3;
}
Console.WriteLine($"[fsmgen] Semantic check OK for {model.Name}");

switch (command)
{
    case "generate-runtime":
        GenerateRuntime(model, outDir);
        break;
    case "generate-tests":
        GenerateTests(model, outDir);
        break;
    case "all":
        GenerateRuntime(model, outDir);
        GenerateTests(model, outDir);
        break;
    default:
        PrintUsage();
        return 1;
}
return 0;

// ===== Команди =====

static void GenerateRuntime(FsmModel model, string outDir)
{
    var className = $"Generated{model.Name}Runtime";
    var sb = new StringBuilder();
    sb.AppendLine($"// AUTO-GENERATED by fsmgen from {model.Name} model");
    sb.AppendLine("// DO NOT EDIT MANUALLY.");
    sb.AppendLine();
    sb.AppendLine("using System;");
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine();
    sb.AppendLine($"public static class {className}");
    sb.AppendLine("{");
    sb.AppendLine($"    public const string InitialState = \"{model.Initial}\";");
    sb.AppendLine();
    sb.AppendLine("    public static readonly Dictionary<(string, string), string> Transitions = new()");
    sb.AppendLine("    {");
    foreach (var t in model.Transitions)
        sb.AppendLine($"        [(\"{t.From}\", \"{t.Event}\")] = \"{t.To}\",");
    sb.AppendLine("    };");
    sb.AppendLine();
    sb.AppendLine("    public static string Next(string state, string evt)");
    sb.AppendLine("    {");
    sb.AppendLine("        if (Transitions.TryGetValue((state, evt), out var next))");
    sb.AppendLine("            return next;");
    sb.AppendLine();
    sb.AppendLine($"        // Unknown policy from DSL: {model.UnknownPolicy}");
    if (model.UnknownPolicy == "ignore")
        sb.AppendLine("        return state;");
    else
        sb.AppendLine("        throw new InvalidOperationException($\"Illegal transition: {state} + {evt}\");");
    sb.AppendLine("    }");
    sb.AppendLine("}");

    var path = Path.Combine(outDir, $"{className}.cs");
    File.WriteAllText(path, sb.ToString());
    Console.WriteLine($"[fsmgen] Generated {path}");
}

static void GenerateTests(FsmModel model, string outDir)
{
    var className = $"Generated{model.Name}Tests";
    var sb = new StringBuilder();
    sb.AppendLine($"// AUTO-GENERATED by fsmgen from {model.Name} model");
    sb.AppendLine("// DO NOT EDIT MANUALLY.");
    sb.AppendLine();
    sb.AppendLine("using System;");
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine();
    sb.AppendLine($"public static class {className}");
    sb.AppendLine("{");
    sb.AppendLine("    static readonly Dictionary<(string, string), string> Transitions = new()");
    sb.AppendLine("    {");
    foreach (var t in model.Transitions)
        sb.AppendLine($"        [(\"{t.From}\", \"{t.Event}\")] = \"{t.To}\",");
    sb.AppendLine("    };");
    sb.AppendLine();
    sb.AppendLine("    static string Next(string s, string e)");
    sb.AppendLine("    {");
    sb.AppendLine("        if (Transitions.TryGetValue((s, e), out var n)) return n;");
    sb.AppendLine("        throw new InvalidOperationException($\"Illegal: {s} + {e}\");");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine("    public static int Run()");
    sb.AppendLine("    {");
    sb.AppendLine("        int passed = 0, total = 0;");
    sb.AppendLine("        void Assert(string name, Func<bool> check)");
    sb.AppendLine("        {");
    sb.AppendLine("            total++;");
    sb.AppendLine("            bool ok;");
    sb.AppendLine("            try { ok = check(); } catch { ok = false; }");
    sb.AppendLine("            if (ok) passed++;");
    sb.AppendLine("            Console.WriteLine($\"  [{(ok ? \\\"PASS\\\" : \\\"FAIL\\\")}] {name}\");");
    sb.AppendLine("        }");
    sb.AppendLine();

    // Valid
    sb.AppendLine("        Console.WriteLine(\"-- Valid --\");");
    foreach (var t in model.Transitions)
    {
        sb.AppendLine($"        Assert(\"{t.From} + {t.Event} -> {t.To}\",");
        sb.AppendLine($"            () => Next(\"{t.From}\", \"{t.Event}\") == \"{t.To}\");");
    }
    sb.AppendLine();

    // Invalid (first 5)
    var validPairs = new HashSet<(string, string)>(
        model.Transitions.Select(t => (t.From, t.Event)));
    var invalid = (from s in model.States
                   from e in model.Events
                   where !validPairs.Contains((s, e))
                   select (s, e)).Take(5).ToList();

    sb.AppendLine("        Console.WriteLine(\"-- Invalid --\");");
    foreach (var (s, e) in invalid)
    {
        sb.AppendLine($"        Assert(\"{s} + {e} throws\",");
        sb.AppendLine($"            () => {{ try {{ Next(\"{s}\", \"{e}\"); return false; }}");
        sb.AppendLine($"                     catch (InvalidOperationException) {{ return true; }} }});");
    }
    sb.AppendLine();

    // Policy
    sb.AppendLine("        Console.WriteLine(\"-- Policy --\");");
    sb.AppendLine($"        Assert(\"Unknown policy '{model.UnknownPolicy}'\",");
    sb.AppendLine("            () => { try { Next(\"X\", \"Y\"); return false; }");
    sb.AppendLine("                     catch (InvalidOperationException) { return true; } });");
    sb.AppendLine();
    sb.AppendLine("        Console.WriteLine($\"\\nPassed: {passed}/{total}\");");
    sb.AppendLine("        return passed == total ? 0 : 1;");
    sb.AppendLine("    }");
    sb.AppendLine("}");

    var path = Path.Combine(outDir, $"{className}.cs");
    File.WriteAllText(path, sb.ToString());
    Console.WriteLine($"[fsmgen] Generated {path}");
}

// ===== Semantic check =====

static List<string> SemanticCheck(FsmModel m)
{
    var errors = new List<string>();
    if (m.States == null || m.States.Count == 0)
        errors.Add("model has no states");
    if (m.Events == null || m.Events.Count == 0)
        errors.Add("model has no events");
    if (m.Transitions == null || m.Transitions.Count == 0)
        errors.Add("model has no transitions");
    if (string.IsNullOrEmpty(m.Initial))
        errors.Add("model has no initial state");
    if (errors.Count > 0) return errors;

    var states = new HashSet<string>(m.States);
    var events = new HashSet<string>(m.Events);
    if (!states.Contains(m.Initial))
        errors.Add($"initial '{m.Initial}' not in states");
    foreach (var t in m.Transitions)
    {
        if (!states.Contains(t.From)) errors.Add($"unknown state '{t.From}'");
        if (!states.Contains(t.To))   errors.Add($"unknown state '{t.To}'");
        if (!events.Contains(t.Event)) errors.Add($"unknown event '{t.Event}'");
    }
    return errors;
}

static void PrintUsage()
{
    Console.WriteLine("Usage:");
    Console.WriteLine("  fsmgen generate-runtime <modelPath> <outDir>");
    Console.WriteLine("  fsmgen generate-tests   <modelPath> <outDir>");
    Console.WriteLine("  fsmgen all              <modelPath> <outDir>");
}

// ===== Типи =====

record FsmModel(
    string Name,
    string Initial,
    string UnknownPolicy,
    List<string> States,
    List<string> Events,
    List<Transition> Transitions);

record Transition(string From, string Event, string To);
